name: OrderedProperties

on:
  schedule:
    # Every Sunday at 9.00am
    - cron: "0 9 * * 0"

  workflow_dispatch:

env:
  GRADLE_ENTERPRISE_URL: "https://ge.solutions-team.gradle.com"
  GRADLE_ENTERPRISE_ACCESS_KEY: "${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}"
  GIT_REPO: "https://github.com/etiennestuder/java-ordered-properties"
  TASKS: "build"

jobs:
  Experiment:

    strategy:
      matrix:
        include:
          - experimentId: 1
          - experimentId: 2
          - experimentId: 3

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
      - name: Download latest version of the validation scripts
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/download@3fb6a3c2c6f2c0836894754b6b8fcef72148c02f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run experiment 1
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-1@3fb6a3c2c6f2c0836894754b6b8fcef72148c02f
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
        if: matrix.experimentId == 1
      - name: Run experiment 2
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-2@3fb6a3c2c6f2c0836894754b6b8fcef72148c02f
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}
          gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
        if: matrix.experimentId == 2
      - name: Run experiment 3
        uses: gradle/gradle-enterprise-build-validation-scripts/.github/actions/gradle/experiment-3@3fb6a3c2c6f2c0836894754b6b8fcef72148c02f
        with:
          gitRepo: ${{ env.GIT_REPO }}
          tasks: ${{ env.TASKS }}          
          gradleEnterpriseUrl: ${{ env.GRADLE_ENTERPRISE_URL }}
        if: matrix.experimentId == 3

  configuration-cache-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project
        uses: actions/checkout@v3
        with:
          repository: "etiennestuder/java-ordered-properties"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "temurin"
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-disabled: true
      - name: Execute Gradle build
        id: gradle-build
        run: |
          # Need to run both builds within same job id to avoid calculating task graph as
          # configuration cache cannot be reused when environment variable 'GITHUB_ACTION' has changed
          ./gradlew --configuration-cache build 2>&1 | tee -a /tmp/gradle-build.log
          echo ::set-output name=configCacheStored::$(grep "Configuration cache entry stored" /tmp/gradle-build.log | wc -l)
          ./gradlew --configuration-cache build 2>&1 | tee -a /tmp/gradle-build.log
          echo ::set-output name=configCacheReused::$(grep "Configuration cache entry reused" /tmp/gradle-build.log | wc -l)
      - name: Fail if Gradle Configuration Cache was not reused
        run: exit 1
        if: steps.gradle-build.outputs.configCacheStored != '1' || steps.gradle-build.outputs.configCacheReused != '1'
