name: Verify Build

on: [ workflow_dispatch ]

jobs:
  verification:
    name: Build Optimization Verification
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Download and Extract Build Validation Scripts
        run: |
          curl -s -L -O https://github.com/gradle/gradle-enterprise-build-validation-scripts/releases/download/v1.0/gradle-enterprise-gradle-build-validation-1.0.zip
          unzip -q -o gradle-enterprise-gradle-build-validation-1.0.zip
      - name: Run Gradle Experiment 1
        run: |
          cd gradle-enterprise-gradle-build-validation
          ./01-validate-incremental-building.sh -r https://github.com/gradle/gradle-build-scan-quickstart -t build -e "https://ge.solutions-team.gradle.com"
